# Generated by Django 2.0.2 on 2018-03-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='createby',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='commentid',
        ),
    ]
