# Generated by Django 2.0.2 on 2018-03-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0002_auto_20180326_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join',
            field=models.ManyToManyField(to='tugether.User'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='createby',
        ),
        migrations.AddField(
            model_name='event',
            name='createby',
            field=models.IntegerField(default=0),
        ),
    ]
