# Generated by Django 2.0.2 on 2018-03-26 05:11

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0003_auto_20180326_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventenddate',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Event End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventstdate',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Event Start Date'),
            preserve_default=False,
        ),
    ]
